// Per-letter layout calibration for each embroidery font: how far a glyph's
// stitch-path data needs to be nudged (offsetY/advanceX/leftBearing) to sit
// correctly relative to its neighbors and the baseline. Calibrated in the
// preview tool at targetHeight=130 as a reference — layout-text.ts scales
// these proportionally to whatever targetHeight is actually rendered.

export type LetterAdj = { offsetY: number; advanceX: number; leftBearing: number; colorableIndices?: number[] };

export const FONT_ADJUSTMENTS: Record<string, Record<string, LetterAdj>> = {
  moonlight: {
  A:{offsetY:18,advanceX:0,leftBearing:0},
  B:{offsetY:0,advanceX:-40,leftBearing:0},
  C:{offsetY:29,advanceX:-46,leftBearing:0},
  D:{offsetY:0,advanceX:-33,leftBearing:0},
  E:{offsetY:0,advanceX:-12,leftBearing:0},
  F:{offsetY:0,advanceX:-74,leftBearing:0},
  G:{offsetY:38,advanceX:-60,leftBearing:0},
  H:{offsetY:44,advanceX:-51,leftBearing:0},
  I:{offsetY:0,advanceX:-37,leftBearing:0},
  J:{offsetY:24,advanceX:-43,leftBearing:0},
  K:{offsetY:0,advanceX:-23,leftBearing:0},
  L:{offsetY:0,advanceX:-7,leftBearing:0},
  M:{offsetY:0,advanceX:-54,leftBearing:0},
  N:{offsetY:10,advanceX:-49,leftBearing:0},
  O:{offsetY:0,advanceX:-22,leftBearing:0},
  P:{offsetY:0,advanceX:-45,leftBearing:0},
  Q:{offsetY:19,advanceX:-9,leftBearing:0},
  R:{offsetY:0,advanceX:-23,leftBearing:0},
  S:{offsetY:15,advanceX:-18,leftBearing:0},
  T:{offsetY:0,advanceX:-68,leftBearing:0},
  U:{offsetY:0,advanceX:-88,leftBearing:0},
  V:{offsetY:0,advanceX:-84,leftBearing:0},
  W:{offsetY:0,advanceX:-84,leftBearing:0},
  X:{offsetY:0,advanceX:-39,leftBearing:0},
  Y:{offsetY:45,advanceX:-9,leftBearing:0},
  Z:{offsetY:30,advanceX:-34,leftBearing:0},
  a:{offsetY:0,advanceX:-17,leftBearing:0},
  b:{offsetY:0,advanceX:-16,leftBearing:0},
  c:{offsetY:0,advanceX:-14,leftBearing:0},
  d:{offsetY:0,advanceX:-32,leftBearing:0},
  e:{offsetY:0,advanceX:-17,leftBearing:0},
  f:{offsetY:36,advanceX:-66,leftBearing:-35},
  g:{offsetY:36,advanceX:-27,leftBearing:-14},
  h:{offsetY:0,advanceX:-26,leftBearing:-6},
  i:{offsetY:0,advanceX:-15,leftBearing:0},
  j:{offsetY:36,advanceX:-51,leftBearing:-34},
  k:{offsetY:0,advanceX:-37,leftBearing:-15},
  l:{offsetY:0,advanceX:-30,leftBearing:0},
  m:{offsetY:0,advanceX:-26,leftBearing:-10},
  n:{offsetY:0,advanceX:-22,leftBearing:-5},
  o:{offsetY:0,advanceX:-18,leftBearing:0},
  p:{offsetY:37,advanceX:-42,leftBearing:-28},
  q:{offsetY:30,advanceX:-17,leftBearing:0},
  r:{offsetY:0,advanceX:-13,leftBearing:3},
  s:{offsetY:0,advanceX:-24,leftBearing:-7},
  t:{offsetY:0,advanceX:-18,leftBearing:0},
  u:{offsetY:0,advanceX:-18,leftBearing:-2},
  v:{offsetY:0,advanceX:-16,leftBearing:0},
  w:{offsetY:0,advanceX:-18,leftBearing:0},
  x:{offsetY:0,advanceX:-23,leftBearing:-6},
  y:{offsetY:28,advanceX:-34,leftBearing:-19},
  z:{offsetY:36,advanceX:-40,leftBearing:-24}
  },
  "alfabeto-liz": {
    A:{offsetY:0,advanceX:0,leftBearing:0}, B:{offsetY:0,advanceX:0,leftBearing:0},
    C:{offsetY:0,advanceX:0,leftBearing:0}, D:{offsetY:0,advanceX:0,leftBearing:0},
    E:{offsetY:0,advanceX:0,leftBearing:0}, F:{offsetY:0,advanceX:0,leftBearing:0},
    G:{offsetY:0,advanceX:0,leftBearing:0}, H:{offsetY:0,advanceX:0,leftBearing:0},
    I:{offsetY:0,advanceX:0,leftBearing:0}, J:{offsetY:0,advanceX:0,leftBearing:0},
    K:{offsetY:0,advanceX:0,leftBearing:0}, L:{offsetY:0,advanceX:0,leftBearing:0},
    M:{offsetY:0,advanceX:0,leftBearing:0}, N:{offsetY:0,advanceX:0,leftBearing:0},
    O:{offsetY:0,advanceX:0,leftBearing:0}, P:{offsetY:0,advanceX:0,leftBearing:0},
    Q:{offsetY:0,advanceX:0,leftBearing:0}, R:{offsetY:0,advanceX:0,leftBearing:0},
    S:{offsetY:0,advanceX:0,leftBearing:0}, T:{offsetY:0,advanceX:0,leftBearing:0},
    U:{offsetY:0,advanceX:0,leftBearing:0}, V:{offsetY:0,advanceX:0,leftBearing:0},
    W:{offsetY:0,advanceX:0,leftBearing:0}, X:{offsetY:0,advanceX:0,leftBearing:0},
    Y:{offsetY:0,advanceX:0,leftBearing:0}, Z:{offsetY:0,advanceX:0,leftBearing:0},
  },
  singular: {
    "!":{offsetY:0,advanceX:0,leftBearing:0},
    "#":{offsetY:0,advanceX:0,leftBearing:0},
    "$":{offsetY:0,advanceX:0,leftBearing:0},
    "%":{offsetY:0,advanceX:0,leftBearing:0},
    "&":{offsetY:0,advanceX:0,leftBearing:0},
    "'":{offsetY:0,advanceX:0,leftBearing:0},
    "(":{offsetY:0,advanceX:0,leftBearing:0},
    ")":{offsetY:0,advanceX:0,leftBearing:0},
    "*":{offsetY:0,advanceX:0,leftBearing:0},
    ",":{offsetY:0,advanceX:0,leftBearing:0},
    "-":{offsetY:0,advanceX:0,leftBearing:0},
    ".":{offsetY:0,advanceX:0,leftBearing:0},
    "/":{offsetY:0,advanceX:0,leftBearing:0},
    "0":{offsetY:0,advanceX:0,leftBearing:0},
    "1":{offsetY:0,advanceX:0,leftBearing:0},
    "2":{offsetY:0,advanceX:0,leftBearing:0},
    "3":{offsetY:0,advanceX:0,leftBearing:0},
    "4":{offsetY:0,advanceX:0,leftBearing:0},
    "5":{offsetY:0,advanceX:0,leftBearing:0},
    "6":{offsetY:0,advanceX:0,leftBearing:0},
    "7":{offsetY:0,advanceX:0,leftBearing:0},
    "8":{offsetY:0,advanceX:0,leftBearing:0},
    "9":{offsetY:0,advanceX:0,leftBearing:0},
    ":":{offsetY:0,advanceX:0,leftBearing:0},
    ";":{offsetY:0,advanceX:0,leftBearing:0},
    "?":{offsetY:0,advanceX:0,leftBearing:0},
    "@":{offsetY:0,advanceX:0,leftBearing:0},
    A:{offsetY:0,advanceX:-7,leftBearing:-12},
    B:{offsetY:0,advanceX:-8,leftBearing:0},
    C:{offsetY:0,advanceX:-14,leftBearing:0},
    D:{offsetY:0,advanceX:-10,leftBearing:0},
    E:{offsetY:0,advanceX:-9,leftBearing:0},
    F:{offsetY:11,advanceX:-27,leftBearing:-10},
    G:{offsetY:16,advanceX:-18,leftBearing:0},
    H:{offsetY:0,advanceX:-23,leftBearing:0},
    I:{offsetY:0,advanceX:-18,leftBearing:0},
    J:{offsetY:11,advanceX:-21,leftBearing:0},
    K:{offsetY:18,advanceX:-25,leftBearing:0},
    L:{offsetY:0,advanceX:-5,leftBearing:-4},
    M:{offsetY:0,advanceX:-19,leftBearing:-6},
    N:{offsetY:21,advanceX:-35,leftBearing:0},
    O:{offsetY:0,advanceX:-9,leftBearing:0},
    P:{offsetY:0,advanceX:-18,leftBearing:0},
    Q:{offsetY:22,advanceX:-21,leftBearing:0},
    R:{offsetY:21,advanceX:-27,leftBearing:0},
    S:{offsetY:0,advanceX:-15,leftBearing:0},
    T:{offsetY:0,advanceX:-33,leftBearing:0},
    U:{offsetY:0,advanceX:-8,leftBearing:0},
    V:{offsetY:0,advanceX:-28,leftBearing:0},
    W:{offsetY:0,advanceX:-26,leftBearing:0},
    X:{offsetY:0,advanceX:-14,leftBearing:-4},
    Y:{offsetY:0,advanceX:-47,leftBearing:0},
    Z:{offsetY:0,advanceX:-6,leftBearing:0},
    a:{offsetY:0,advanceX:-8,leftBearing:0},
    b:{offsetY:0,advanceX:-8,leftBearing:0},
    c:{offsetY:0,advanceX:-6,leftBearing:0},
    d:{offsetY:0,advanceX:-24,leftBearing:-5},
    e:{offsetY:0,advanceX:-7,leftBearing:0},
    f:{offsetY:39,advanceX:-25,leftBearing:-30},
    g:{offsetY:39,advanceX:-18,leftBearing:-26},
    h:{offsetY:0,advanceX:-7,leftBearing:0},
    i:{offsetY:0,advanceX:-10,leftBearing:4},
    j:{offsetY:39,advanceX:-40,leftBearing:-26},
    k:{offsetY:20,advanceX:-23,leftBearing:-2},
    l:{offsetY:0,advanceX:-25,leftBearing:0},
    m:{offsetY:0,advanceX:-7,leftBearing:0},
    n:{offsetY:0,advanceX:-7,leftBearing:0},
    o:{offsetY:0,advanceX:-7,leftBearing:0},
    p:{offsetY:38,advanceX:-8,leftBearing:0},
    q:{offsetY:37,advanceX:-8,leftBearing:0},
    r:{offsetY:0,advanceX:-16,leftBearing:0},
    s:{offsetY:0,advanceX:-13,leftBearing:-3},
    t:{offsetY:0,advanceX:-8,leftBearing:0},
    u:{offsetY:0,advanceX:-11,leftBearing:0},
    v:{offsetY:0,advanceX:-9,leftBearing:0},
    w:{offsetY:0,advanceX:-10,leftBearing:0},
    x:{offsetY:18,advanceX:-10,leftBearing:0},
    y:{offsetY:37,advanceX:-15,leftBearing:-13},
    z:{offsetY:0,advanceX:-7,leftBearing:0},
    "¡":{offsetY:0,advanceX:0,leftBearing:0},
  },
};
